(function(g){var window=this;'use strict';var U3=function(a){a.oa("cardstatechange",a.Pk()&&a.ip()?1:0)},V3=function(a,b){var c=g.Ya(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},xkb=function(a){var b=g.ds(a);
a=g.gs(a);return new g.Tr(b.x,b.y,a.width,a.height)},ykb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.AC(a,b,function(){g.BC(e);c.apply(a,arguments)},d)},Y3=function(a){a=g.db(a);
delete W3[a];g.id(W3)&&X3&&X3.stop()},Akb=function(){X3||(X3=new g.Cu(function(){zkb()},20));
var a=X3;a.isActive()||a.start()},zkb=function(){var a=g.gb();
g.Wc(W3,function(b){Bkb(b,a)});
g.id(W3)||Akb()},Z3=function(a,b,c,d){g.Wu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Bkb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Ckb(a,a.progress);1==a.progress?(a.j=0,Y3(a),a.onFinish(),a.zr()):a.isPlaying()&&a.tL()},Ckb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Dkb=function(a,b){g.yb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},$3=function(a,b,c,d,e){Z3.call(this,b,c,d,e);
this.element=a},Ekb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$3.call(this,a,b,c,d,e)},Fkb=function(a){return Math.pow(a,3)},Gkb=function(a){return 3*a*a-2*a*a*a},Hkb=function(a){g.H.call(this);
this.B=a||window;this.j=[]},a4=function(a){return a.baseUrl||null},b4=function(a,b){return g.$s(g.nr(a,b),function(c){return!!c})},Ikb=function(a,b,c){function d(sa){var ma=sa.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var pa=f(ma.unsubscribedButtonText),ba=f(ma.subscribedButtonText);if(ma.subscribed){var T=f(ma.subscriberCountWithUnsubscribeText);var Ma=f(ma.subscriberCountText)}else T=f(ma.subscriberCountText),Ma=f(ma.subscriberCountWithSubscribeText);var y=null;if(sa.signinEndpoint){y=V3(sa,"signinEndpoint","webNavigationEndpointData","url");if(!y){var Z,Ua;y=null==(Ua=g.R(null==(Z=ma.signInEndpoint)?void 0:Z.commandMetadata,g.M2))?void 0:Ua.url}if(!y)return null}return pa&&
(ba||y)?{subscribed:ma.subscribed,subscribeText:pa,subscribeCount:T,unsubscribeText:ba,unsubscribeCount:Ma,enabled:ma.enabled,signinUrl:y,classic:sa.useClassicSubscribeButton}:null}
function e(sa){if(sa){var ma=[],pa=sa.videoId;pa&&ma.push("v="+pa);(pa=sa.playlistId)&&ma.push("list="+pa);(sa=sa.startTimeSeconds)&&ma.push("t="+sa);return"/watch?"+ma.join("&")}}
function f(sa){if(!sa)return null;var ma=sa.simpleText;return ma?ma:sa.runs?g.nr(sa.runs,function(pa){return pa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,B=null,F=null,G=null,I=null,L=null,Q=null;if("VIDEO"===h)g.R(l,g.lG)?m=g.R(l,g.lG).url:(Q=g.R(l,g.mT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.R(l,g.lG)?m=g.R(l,g.lG).url:(Q=g.R(l,g.mT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=V3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((G=V3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=V3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=V3(b,"title","accessibility","accessibilityData","label");var V=b.endpoint?b.endpoint.clickTrackingParams:null,
ka="";if(b.metadata){var ra=f(b.metadata);ra&&(ka=ra)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ka,callToAction:f(b.callToAction),KV:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,bE:p,playlistLength:t,channelId:v,subscribeButton:B,subscribersText:F,isSubscribe:x,targetUrl:m||null,C7:n,sessionData:V?{itct:V}:null,Xba:q,IC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:b4(b.impressionUrls||[],a4),q7:b4(b.hovercardShowUrls||[],a4),clickUrls:b4(l.loggingUrls||[],a4),visualElement:g.pF(b.trackingParams),productPrice:I,additionalFeesText:L,watchEndpoint:Q||null}},Jkb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:b4(a.impressionUrls||[],a4),elements:b4(a.elements||[],function(d,e){return Ikb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.pF(a.trackingParams));return c},Kkb=function(a){g.FV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.dS(a)||g.fS(a);this.events=new g.MK(this);g.J(this,this.events);this.events.T(this.player,g.XJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.YJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Kb);this.events.T(window,"focus",this.iaa);this.load();var b=g.$e("STYLE");(g.Je("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.nf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Lkb=function(a){return a.player.getVideoData().Jf?"current":a.Z?"new":"current"},c4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Mkb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Jkb(f,Lkb(a))));d4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Nx;d&&(c.postParams={ad_tracking:d});if(b=g.qSa(b))if(b=g.Hn(b),b=g.Vd(b))a.C=g.SB(b,c)},d4=function(a,b,c){c=void 0===c?!0:c;
a.player.lf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Nkb(a);c=[];d=new g.WJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.U({I:"div",S:"ytp-ce-shadow"}),g.uU(a.player,a.B.element,4),a.D=new g.yG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Okb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.uU(a.player,f.element,4);var h=new g.WJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Pkb(a,f,e)}else g.vF(new g.RC("buildEndscreenElement null",
e))}a.player.tf(c);a.Kb()}},Nkb=function(a){var b=g.qF(),c=g.rF();
c&&b&&a.endscreen.visualElement&&g.AB(g.FF)(void 0,c,b,a.endscreen.visualElement)},Okb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.IC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.av(b.title||"")},ya:b.title},{I:"div",S:b.bE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.IC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.av(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.IC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.av(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)}]};c=new g.U(c);var d=g.Ke(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Ku(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.nW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.IC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.av(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Qkb(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.IC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.av(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.Ku(c.element,"ytp-ce-placeholder");return c},e4=function(a){if(a.KV)var b=a.KV.thumbnails;
return Qkb(b?b[b.length-1].url:null)},Qkb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Pkb=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Ku(b.element,"ytp-ce-force-expand"),g4(a,c.id,!0)):(g.Mu(b.element,"ytp-ce-force-expand"),g.Mu(b.element,"ytp-ce-element-hover"),g4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){Rkb(a,b,c)});
b.Ra("mouseleave",function(){Skb(a,b,c)});
a.player.U().B||b.Ra("click",function(){g.Ku(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){Tkb(a,c,m)});
b.Ra("keypress",function(m){Tkb(a,c,m)});
b.Ra("focus",function(){Rkb(a,b,c)});
b.Ra("blur",function(){Skb(a,b,c)});
b.Ra("touchstart",function(){Rkb(a,b,c)});
var l=g.Me("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Mu(b.element,"ytp-ce-element-hover");g.Mu(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Me("ytp-sb-subscribe",b.element));d(g.Me("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},Tkb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Ju(d,"ytp-ce-element");){g.Ju(d,"subscribe-label")&&Ukb(a,b);
if(g.Ju(d,"ytp-ce-channel-subscribe"))return;d=g.of(d)}if(!d||g.Ju(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Skb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Xba)Ukb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Hn(f4(a,b.targetUrl)),g.$G(g.Vd(c),void 0,b.sessionData);else{var e=g.pS(a.player.U())||a.player.getVideoData().Jf,f=function(){var h=f4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.FB(h);e&&n&&(n.v||
n.list)?a.player.Ko(n.v,l,n.list,!1,void 0,m||void 0):g.Lwa(h,l)};
Ukb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},f4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.wS(a)+b}else return"";return b},Rkb=function(a,b,c){g.Ju(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Ku(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Cu(function(){g.Ku(b.element,"ytp-ce-element-hover")},200)).start():g.Ku(b.element,"ytp-ce-element-hover"),h4(a,c.q7),g4(a,c.id,!0))},Skb=function(a,b,c){g.Mu(b.element,"ytp-ce-element-hover");
g.Mu(b.element,"ytp-ce-force-expand");g4(a,c.id,!1)},g4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Ou(a.j[e].element,"ytp-ce-element-shadow-show",c)},h4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||c4(a))c&&c();else{b=Vkb(a,b);var e=0,f=!1,h=new g.Cu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.kE(b[a],d)}},Ukb=function(a,b,c){h4(a,b.clickUrls,c);
(a=g.rF())&&b.C7&&g.MF(a,b.visualElement)},Vkb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Wkb(b[d],c));return a},Wkb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Xkb=function(a){return"string"===typeof a?a:""},i4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Ykb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},j4=function(a){return a.value?a.value:null},k4=function(a){if(!a)return null;
var b=g.Hn(Xkb(a.value));b=g.Vd(b);if(!b)return null;var c=i4(a.target,Zkb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Ykb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$kb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},clb=function(a){if(!a)return null;
var b=i4(a.type,alb),c=i4(a.trigger,blb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=k4(a?a:null);return b?new $kb(b,c,a):null},dlb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},elb=function(a,b){return g.Db(a.action,b)},flb=function(a,b){this.context=a;
this.j=b},glb=function(a){return a.customMessage?l4("div","iv-card-message",a.customMessage):""},m4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},hlb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(l4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},l4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.av(c);return{I:a,W:b,ya:c}},ilb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.RC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.RC+");");c.dir=g.av(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,W:c,V:d}},n4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.ej.click,5)}},jlb=function(a,b){this.merchant=a;
this.price=b},klb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},llb=function(a,b){return b?b:klb(a)?"current":"new"},o4=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Xa=new Map;this.Za=new Map;this.context.J.addEventListener(g.XJ("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.YJ("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},p4=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.uL(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.rb=!1});
a.context.j.Ra(b,"touchmove",function(){a.rb=!0})},mlb=function(a){var b;
return(null==(b=g.R(a,g.lG))?0:b.url)?g.R(a,g.lG).url:(a=g.R(a,g.mT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},q4=function(a,b,c){return{kX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
N_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
NK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},nlb=function(a,b,c){o4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Cb=this.Na=this.Tb=this.C=this.isInitialized=!1;this.cards=[];this.tb=this.Z=this.La=this.G=this.Va=this.j=null;this.ma=[];this.qa=this.N=this.Hf=this.Ia=null;this.K=0;this.Ga=new g.Cu(function(){},c.X.Qi?4E3:3E3);
g.J(this,this.Ga);this.ob=new g.Cu(function(){});
g.J(this,this.ob);this.Aa=new flb(c,function(e,f,h,l,m,n){p4(d,e,f,h,l,m,n)});
this.Y=new g.U({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.J(this,this.Y);this.D=this.Y.element;this.bb=new g.yG(this.Y,330);g.J(this,this.bb);this.Ib=g.Me("iv-drawer-header-text",this.D);this.B=g.Me("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Tb&&r4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Tb=d.C)&&s4(d)});
this.Qa=new g.MK(this);g.J(this,this.Qa);this.J.addEventListener("videodatachange",this.vt.bind(this))},olb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){r4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){s4(a)});
var c=b.headerText;g.qf(a.Ib,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.pF(b.trackingParams);a.N=g.pF(b.closeTrackingParams);a.Hf=g.pF(b.iconTrackingParams)},plb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.ib("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.$F(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,ej:{},kp:null,Mj:e.trackingParams?g.pF(e.trackingParams):null,Hf:f&&f.trackingParams?g.pF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
RC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};t4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.$F(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:u4(a,c,b,f),sponsored:!1,ej:q4(f,e,f.command),kp:f.trackingParams?g.pF(f.trackingParams):null,Mj:e.trackingParams?g.pF(e.trackingParams):null,Hf:l&&l.trackingParams?g.pF(l.trackingParams):null,imageUrl:v4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.$F(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,RC:null,title:f.title?g.$F(f.title):"",customMessage:f.callToAction?g.$F(f.callToAction):"",url:g.R(f.command,g.lG).url?k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(f.command,g.lG).url}):null,onClickCommand:null};t4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.$F(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,ej:q4(e,f,e.endpoint),kp:e.trackingParams?g.pF(e.trackingParams):null,Mj:f.trackingParams?g.pF(f.trackingParams):null,Hf:l&&l.trackingParams?g.pF(l.trackingParams):null,channelId:g.R(e.endpoint,g.SU).browseId,customMessage:e.customText?g.$F(e.customText):null,profileImageUrl:v4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.$F(e.channelName):"",metaInfo:[e.subscriberCountText?g.$F(e.subscriberCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(e.endpoint,g.SU).canonicalBaseUrl?g.R(e.endpoint,g.SU).canonicalBaseUrl:"/channel/"+g.R(e.endpoint,g.SU).browseId}),onClickCommand:null};t4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.$F(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,ej:q4(e,f,e.action),kp:e.trackingParams?g.pF(e.trackingParams):null,Mj:f.trackingParams?g.pF(f.trackingParams):null,Hf:l&&l.trackingParams?g.pF(l.trackingParams):null,VF:v4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.$F(e.customMessage):null,playlistVideoCount:g.$F(e.playlistVideoCount),title:e.playlistTitle?g.$F(e.playlistTitle):"",metaInfo:[e.channelName?g.$F(e.channelName):
"",e.videoCountText?g.$F(e.videoCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mlb(e.action)}),onClickCommand:null};t4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.$F(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,ej:q4(e,f,e.action),kp:e.trackingParams?g.pF(e.trackingParams):null,Mj:f.trackingParams?g.pF(f.trackingParams):null,Hf:l&&l.trackingParams?g.pF(l.trackingParams):null,VF:v4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.$F(e.lengthString):null,customMessage:e.customMessage?g.$F(e.customMessage):null,title:e.videoTitle?g.$F(e.videoTitle):"",metaInfo:[e.channelName?g.$F(e.channelName):
"",e.viewCountText?g.$F(e.viewCountText):""],isLiveNow:!!e.badge,url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mlb(e.action)}),onClickCommand:null};t4(a,b)}}}}}a.K++},v4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},u4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},rlb=function(a,b){if(b=qlb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.gg.id),g.nf(b.LM),g.Hb(a.cards,b),a.UG(),w4(a)},r4=function(a,b,c){if(!a.C){a.bb.show();
a.Va=new g.Cu(function(){g.Ku(a.context.J.getRootNode(),g.ZY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Qa.T(a.B,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.rF();d&&a.Ia&&a.N&&g.KF(d,[a.Ia,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.aY||(f.aY=!0,slb(a.context.logger,f.gg.ej.kX,b)),d&&g.KF(d,[f.gg.kp]);U3(a.J);c&&(a.G=new g.Cu(function(){a.La=a.Z;a.tb.focus()},330),a.G.start())}},s4=function(a){a.C&&(a.bb.hide(),g.GC(a.Qa),g.Mu(a.context.J.getRootNode(),g.ZY.IV_DRAWER_OPEN),a.C=!1,U3(a.J),a.G&&a.G.stop(),a.G=new g.Cu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},ulb=function(a){g.Lu(a.Ab(),
[g.ZY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.uU(a.J,a.D,5);tlb(a);a.Z=g.Me("ytp-cards-button",a.J.getRootNode());a.tb=g.Me("iv-drawer-close-button",a.D);a.isInitialized=!0},tlb=function(a){var b=g.Me("iv-drawer-close-button",a.D);
a.context.j.Ra(b,"click",a.e5,a);a.context.j.Ra(a.B,"touchend",function(){a.Ga.start()});
a.context.j.Ra(a.B,"scroll",a.B5,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Ju(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.yE("iv-button-shown",a.T7,a));a.ma.push(g.yE("iv-button-hidden",a.S7,a));vlb(a)},vlb=function(a){a.ma.push(g.yE("iv-teaser-shown",a.I1,a));
a.ma.push(g.yE("iv-teaser-hidden",a.U7,a));a.ma.push(g.yE("iv-teaser-clicked",a.H1,a));a.Cb=!0},wlb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.R(b.onClickCommand,g.Xgb))?void 0:c.targetId)?(a.qa=b,!0):!1},xlb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.PQa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.R(h[0],g.QZa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},t4=function(a,b){if(!wlb(a,b)||xlb(a,b)){var c=ylb(a,b);
if(c){var d={gg:b,LM:c.element,aY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Cb||vlb(a),rlb(a,b.id),c=zlb(a,d),g.Nb(a.cards,c,0,d));else{a.isInitialized||ulb(a);rlb(a,b.id);var e=zlb(a,d);g.Nb(a.cards,e,0,d);c.Da(a.B,e);a.UG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,w4(a),Alb(a,d),r4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Blb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Blb(a,
d)}),w4(a))}}},ylb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=ilb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?j4(b.url)||"":""},V:[m4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[l4("h2",void 0,b.title),d]}]}]};c=new g.U(c);n4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],W:{href:j4(b.url)||"","data-ytid":b.channelId},V:[m4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[glb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},hlb(b)]}]}]};c=new g.U(c);n4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:j4(b.url)||""},V:[m4(b.VF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[glb(b),l4("h2","iv-card-primary-link",b.title),hlb(b)]}]}]};
c=new g.U(c);n4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=ilb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?j4(b.url)||"":"";c={I:"div",Ma:c,W:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[l4("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.$e("span");g.qf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.ge(d,"adInfo");n4(a,g.Le("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:(null==(c=b.url)?void 0:j4(c))||""},V:[m4(b.VF,d),{I:"div",S:"iv-card-content",V:[glb(b),l4("h2","iv-card-primary-link",b.title),hlb(b),f]}]}]};c=new g.U(e);n4(a,g.Le("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},zlb=function(a,b){if(0===a.cards.length)return 0;
a=g.Eb(a.cards,function(c){return b.gg.startMs>c.gg.startMs||b.gg.startMs===c.gg.startMs&&b.gg.timestamp>=c.gg.timestamp?!0:!1});
return-1===a?0:a+1},Clb=function(a){if(a.j)return"productListing"===a.j.gg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.or(a.cards,function(c){return"productListing"===c.gg.type})}return g.or(a.cards,function(c){return"productListing"===c.gg.type})},w4=function(a){g.Ou(a.J.getRootNode(),"ytp-cards-shopping-active",Clb(a))},Blb=function(a,b){if(!g.Ju(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.rF(),d=a.j?a.j.gg.Hf:a.Hf;
c&&d&&g.LF(c,[d]);a.j=b;w4(a)}(c=a.isInitialized&&"none"==a.Ab().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.gg.teaserDurationMs&&a.J.qB(!0,{teaserText:b.gg.teaserText,durationMs:b.gg.teaserDurationMs,onClickCommand:b.gg.onClickCommand});a.ob.isActive()||((!a.C||!a.Ga.isActive()&&a.Na)&&Alb(a,b),a.ob.start(910+b.gg.teaserDurationMs))}},Alb=function(a,b){a.Y.Eb?(b=new Z3([0,
a.B.scrollTop],[0,b.LM.offsetTop],600,Gkb),a.context.C.Ra(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ra(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.WF(a.Y,!0),a.B.scrollTop=b.LM.offsetTop,g.WF(a.Y,!1))},x4=function(a){return a.j&&a.j.gg?a.j.gg:a.cards[0]&&a.cards[0].gg?a.cards[0].gg:null},qlb=function(a,b){return g.Db(a.cards,function(c){return c.gg.id===b})},y4=function(a,b,c){o4.call(this,a,b);
this.annotation=c;this.isActive=!1},Dlb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},z4=function(a,b,c){y4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Elb=function(a,b){var c=void 0===c?0:c;
var d=xkb(b).width;g.bs(b,d);c=new Ekb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Fkb);g.J(a,c);a.context.C.Ra(c,"begin",function(){g.hs(b,!0)});
c.play()},Hlb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.nW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Da(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.hs(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Wr(l,"right",b.image_width+"px");g.bf(a.Ab(),l);a.C=new g.Cu(function(){Flb(a,h,l)},500);
g.J(a,a.C);a.context.j.Ra(a.Ab(),"mouseover",function(){Glb(a,h,l,f,b.image_height)});
a.context.j.Ra(a.Ab(),"mouseout",function(){a.C.start()})}},Glb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.gs(b);a.j||(b.style.width=g.as(f.width,!0),c.style.width=g.as(f.width,!0));g.Wr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Wr(d,"right","1px");a.D=!0;g.hs(b,!0);a.G=new g.Cu(function(){g.Ku(this.Ab(),"iv-branding-active")},0,a);
a.G.start()}},Flb=function(a,b,c){g.Mu(a.Ab(),"iv-branding-active");
a.K=new g.Cu(function(){g.hs(b,!1);a.j||(c.style.width=g.as(0,!0))},250);
a.K.start();a.D=!1},Ilb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Jlb=function(a,b,c){y4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Cu(function(){d.j.setAttribute("aria-hidden","true");g.hs(d.C,!1);g.hs(d.B,!0)},700,this);
g.J(this,this.G)},Mlb=function(a,b,c){c.stopPropagation();
Klb(a);Llb(a,b);a.j.focus()},Nlb=function(a){a.isCollapsed||a.Z||a.D||(g.Ku(a.Ab(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Klb=function(a){a.G.stop();
a.isCollapsed&&(g.Nu(a.Ab(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.hs(a.B,!1),g.hs(a.C,!0))},Llb=function(a,b){a.D||(a.D=g.ag(function(){Olb(this);
Nlb(this)},b,a))},Olb=function(a){a.D&&(g.Qa.clearTimeout(a.D),a.D=null)},Plb=function(a){this.J=a},slb=function(a,b,c){b&&(c?A4(a,b.map(function(d){return g.qu(d,c)})):A4(a,b))},A4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.kE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Qlb=function(a){g.FV.call(this,a);
var b=this;this.Y=this.N=!1;this.loadNumber=0;this.K={};this.logger=new Plb(this.player);this.D=new g.MK(this);this.G=this.Bx=null;this.events=new g.MK(this);this.Vg=this.Z=this.j=null;this.ma=[];g.J(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.J1,this);this.subscribe("resize",this.AJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.lZ,this);g.J(this,this.events);this.qa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.U({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.B);g.uU(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Ma:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.qa);this.C.element.appendChild(a);this.vu()&&this.load();var c=this.createElement({I:"style"});(g.Je("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.nf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Rlb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.hs(a,!1);return a},Slb=function(a,b){b=!b.isCued()&&!g.FG(b,1024);
g.WF(a.B,b);g.WF(a.C,b)},Tlb=function(a,b,c){a.N=!0;
a.G=g.SB(b,c)},Ulb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.$a(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ulb(a,e))}return c},Ylb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.MB(h)&&h.responseXML?h.responseXML:null)&&Vlb(a,h)}};
g.ZC()&&(d.onFinish=Wlb(a,d.onFinish));d.postParams={ic_only:"1"};Xlb(d,c);a.N=!0;g.SB(b.Xa,d)}}},Xlb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.ZG&&(a.postParams.ic_coll=b.ZG);b.MM&&(a.postParams.ic_xml=b.MM);b.SK&&(a.postParams.ic_track=b.SK)},Zlb=function(a){var b=new g.U({I:"div"});
g.hs(b.element,!1);var c=new nlb(a.player,b.element,B4(a));g.J(c,b);b.Da(a.B.element);c.JF();return c},amb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.Y=!0,$lb(a,b),b.headerText&&a.Vg&&(c=g.$F(b.headerText),a.Vg.setAttribute("title",c))},B4=function(a){if(!a.Z){var b=new Hkb(a);
g.J(a,b);var c=new g.ap(a);g.J(a,c);a.Z=new Ilb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.tj)}return a.Z},Vlb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.rF();if(e){var f=g.qF();f&&g.AB(g.lva)(void 0,e,f,[g.pF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Ulb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=i4(f.type,bmb),p=i4(f.style,cmb),q=Xkb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=clb;if(null==t)var v=null;else if(g.Ya(t)){l=[];for(var x=g.u(t),B=x.next();!B.done;B=x.next()){var F=f(B.value);
F&&l.push(F)}v=l}else{var G=f(t);v=G?[G]:[]}e=m&&n?new dlb(m,n,p,v,r):null}else e=null}catch(ra){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=Rlb(f),L=null;switch(l.type){case "branding":if(f.player.U().ze)break;f.B.element.appendChild(I);L=new z4(I,B4(f),l);break;case "promotion":g.uU(f.player,I,4),L=new Jlb(I,B4(f),l)}L&&L.JF();if(f=L)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Zlb(a),g.J(a,a.j));if("card"===e.type){I=a.j;var Q=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(Q)switch(f=e.tracking||{},f={kX:f.impression,click:f.click,close:f.close,N_:f.teaser_impression,NK:f.teaser_click},l=e.tracking_params||{},L=null,Q){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,kp:l.card?g.pF(l.card):null,Mj:l.teaser?g.pF(l.teaser):null,Hf:l.icon?g.pF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:k4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};t4(I,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,
kp:l.card?g.pF(l.card):null,Mj:l.teaser?g.pF(l.teaser):null,Hf:l.icon?g.pF(l.icon):null,VF:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:k4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};t4(I,c);break;case "productListing":e.signin_url&&(L=k4({target:"current",value:e.signin_url}));Q=[];for(var V=e.offers||[],ka=0;ka<V.length;ka++)Q.push(new jlb(g.ue(V[ka].merchant),
g.ue(V[ka].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,kp:l.card?g.pF(l.card):null,Mj:l.teaser?g.pF(l.teaser):null,Hf:l.icon?g.pF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,RC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:k4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Skb:L,Rkb:e.signin_title?e.signin_title:void 0,Qkb:e.signin_message?e.signin_message:void 0,offers:Q,onClickCommand:null};t4(I,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,kp:l.card?g.pF(l.card):
null,Mj:l.teaser?g.pF(l.teaser):null,Hf:l.icon?g.pF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,RC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:k4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};t4(I,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,kp:l.card?g.pF(l.card):null,Mj:l.teaser?g.pF(l.teaser):null,Hf:l.icon?g.pF(l.icon):null,VF:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:k4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},t4(I,c)}}else olb(a.j,e);c=!0}}c&&
(U3(a.player),a.AJ())},$lb=function(a,b){var c=!1;
a.j||(a.j=Zlb(a),g.J(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(plb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.HT(f)||(c=a.j,d=b.headerText?g.$F(b.headerText):"",g.qf(c.Ib,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.pF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.pF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Hf=b.icon.infoCardIconRenderer.trackingParams?g.pF(b.icon.infoCardIconRenderer.trackingParams):null,a.AJ());U3(a.player)}},dmb=function(a,b,c,d,e){if(!a.player.U().ze){var f=[];
b.navigationEndpoint&&g.R(b.navigationEndpoint,g.SU)&&g.R(b.navigationEndpoint,g.SU).browseId&&f.push(new $kb("openUrl","click",new Ykb("/channel/"+g.R(b.navigationEndpoint,g.SU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.R(b.subscribeButton,
g.AT)){d.channel_id=g.R(b.subscribeButton,g.AT).channelId;var l;b=g.R(b.subscribeButton,g.AT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.$F(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.$F(b.subscriberCountText))):(b.subscriberCountText&&(e=g.$F(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.$F(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.R(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.M2))?void 0:m.url)||"";l={subscribeText:g.$F(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.$F(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new dlb(c,"branding","branding",f,d);l=Rlb(a);a.B.element.appendChild(l);f=new z4(l,B4(a),f);f.JF();g.J(f,f);a.K[c]=f}},Wlb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ma.push(g.uu.Si(function(){b.apply(null,g.na(c))}))}},emb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.mU.prototype.qB=g.ca(29,function(a,b){var c=g.VV(this.zb());c&&c.qB(a,b)});
var W3={},X3=null;g.ib(Z3,g.Wu);g.k=Z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;Y3(this);this.startTime=a=g.gb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.sJ();this.fm("play");this.isPaused()&&this.fm("resume");this.j=1;var b=g.db(this);b in W3||(W3[b]=this);Akb();Bkb(this,a);return!0};
g.k.stop=function(a){Y3(this);this.j=0;a&&(this.progress=1);Ckb(this,this.progress);this.fm("stop");this.zr()};
g.k.pause=function(){this.isPlaying()&&(Y3(this),this.j=-1,this.fm("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.fm("destroy");Z3.Of.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.tL=function(){this.fm("animate")};
g.k.fm=function(a){this.dispatchEvent(new Dkb(a,this))};
g.ib(Dkb,g.yb);g.ib($3,Z3);$3.prototype.C=function(){};
$3.prototype.tL=function(){this.C();$3.Of.tL.call(this)};
$3.prototype.zr=function(){this.C();$3.Of.zr.call(this)};
$3.prototype.sJ=function(){this.C();$3.Of.sJ.call(this)};
g.ib(Ekb,$3);Ekb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Hkb,g.H);g.k=Hkb.prototype;g.k.Ra=function(a,b,c,d){c=(0,g.eb)(c,d||this.B);a=g.AC(a,b,c);this.j.push(a);return a};
g.k.UI=function(a,b,c,d){c=(0,g.eb)(c,d||this.B);a=ykb(a,b,c);this.j.push(a);return a};
g.k.Lc=function(a){g.BC(a);g.Hb(this.j,a)};
g.k.Mf=function(){g.BC(this.j);this.j.length=0};
g.k.xa=function(){this.Mf();g.H.prototype.xa.call(this)};g.w(Kkb,g.FV);g.k=Kkb.prototype;g.k.load=function(){g.FV.prototype.load.call(this);if(!c4(this)){var a=g.rSa(this.player.getVideoData());a?(a=Jkb(a,Lkb(this)),d4(this,a,!1)):Mkb(this)}};
g.k.unload=function(){d4(this,null);this.C&&(this.C.abort(),this.C=null);g.FV.prototype.unload.call(this)};
g.k.Kh=function(a,b){return c4(this)?"loadCustomEndscreenRenderer"===a?(a=Jkb(b,"new"),d4(this,a),!0):null:null};
g.k.getOptions=function(){return c4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Kb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<fmb.length;f++){var h=Math.abs(b.width-fmb[f]);if(-1===e||d>=h)e=f,d=h}d=gmb[e];this.B&&g.Wr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.fs(e.element,m,f);g.bs(e.element,n,p);g.Nu(e.element,hmb);256<m||256<f?g.Ku(e.element,"ytp-ce-large-round"):96<m||96<f?g.Ku(e.element,"ytp-ce-medium-round"):g.Ku(e.element,"ytp-ce-small-round");g.Nu(e.element,imb);m=h.left+h.width/2;h=h.top+l/2;g.Ku(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Nu(e.element,gmb);g.Ku(e.element,d);(e=g.Ke(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Wr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())h4(this,this.endscreen.impressionUrls),(a=g.rF())&&this.endscreen.visualElement&&g.JF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Ku(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Ku(b,"ytp-ce-shown");h4(this,c.impressionUrls);(b=g.rF())&&g.JF(b,c.visualElement);this.player.U().K&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Mu(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Mu(b,"ytp-ce-shown");this.player.U().K&&this.player.jb("endscreenelementhidden",a)}};
g.k.iaa=function(a){var b=this;a.target===window&&(new g.Cu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Nu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var fmb=[346,426,470,506,570,640,853,1280,1920],gmb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),imb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],hmb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Zkb={Jsa:"current",aTa:"new"};var alb={CLOSE:"close",DWa:"openUrl",SUBSCRIBE:"subscribe"},blb={Yqa:"click",CLOSE:"close",kEa:"hidden",S0a:"rollOut",T0a:"rollOver",D2a:"shown"};dlb.prototype.gf=function(){var a=elb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var cmb={Pla:"anchored",X0:"branding",CHANNEL:"channel",zsa:"cta",nEa:"highlightText",oIa:"label",PLAYLIST:"playlist",kZa:"popup",C5a:"speech",SUBSCRIBE:"subscribe",l9a:"title",VIDEO:"video",Kfb:"website"},bmb={X0:"branding",Noa:"card",Nua:"drawer",mEa:"highlight",yOa:"marker",N_a:"promotion",TEXT:"text",phb:"widget"};g.w(o4,g.H);g.k=o4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.WJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.Za.set(a,e);this.context.J.tf([a])};
g.k.JF=function(){this.context.B.subscribe("resize",this.UG,this)};
g.k.Ab=function(){return this.element};
g.k.uL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.nf(this.Ab())};
g.k.UG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=j4(a);if(f){var h=llb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Jf||!1,n=g.FB(f||"");m&&n&&(n.v||n.list)?e.context.J.Ko(n.v,b,n.list,!1):g.$G(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);A4(this.context.logger,c,l,d);klb(f)||(c=g.rF(),d=b.itct,c&&d&&g.MF(c,g.pF(d)))}};
g.k.xa=function(){this.Xa.clear();this.Za.clear();g.H.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.w(nlb,o4);g.k=nlb.prototype;g.k.vt=function(){this.qa&&t4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.gs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.UG=function(){var a=this.isAvailable();g.hs(this.Ab(),a);g.Ou(this.context.J.getRootNode(),g.ZY.IV_DRAWER_ENABLED,a);U3(this.J)};
g.k.destroy=function(){this.J.qB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.zE(this.ma);g.GC(this.Qa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();o4.prototype.destroy.call(this)};
g.k.e5=function(){if(this.C){A4(this.context.logger,x4(this).ej.close);var a=g.rF();a&&this.N&&g.MF(a,this.N);s4(this)}};
g.k.B5=function(){g.Ou(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.T7=function(){var a=g.rF(),b=x4(this);b=b?b.Hf:this.Hf;a&&b&&g.KF(a,[b])};
g.k.S7=function(){var a=g.rF(),b=x4(this);b=b?b.Hf:this.Hf;a&&b&&g.LF(a,[b])};
g.k.I1=function(){var a=x4(this);A4(this.context.logger,a.ej.N_);var b=g.rF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Mj&&c.push(a.Mj);a.Hf&&c.push(a.Hf);0<c.length&&g.KF(b,c)}else g.KF(b,[a.Mj,a.Hf])};
g.k.U7=function(){var a=g.rF(),b=x4(this);a&&b&&g.LF(a,[b.Mj])};
g.k.H1=function(a){var b=x4(this),c=g.rF();this.j?a?(a=this.context.logger,A4(a,b.ej.NK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Mj&&g.MF(c,b.Mj)):(a=this.context.logger,A4(a,b.ej.NK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Hf&&g.MF(c,b.Hf)):(a=this.context.logger,A4(a,b.ej.NK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Hf&&g.MF(c,this.Hf))};g.w(y4,o4);y4.prototype.JF=function(){o4.prototype.JF.call(this);Dlb(this)};
y4.prototype.show=function(){o4.prototype.show.call(this);var a=g.rF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.KF(a,[g.pF(b.itct)])};
y4.prototype.hide=function(){o4.prototype.hide.call(this);var a=g.rF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.LF(a,[g.pF(b.itct)])};g.w(z4,y4);z4.prototype.iB=function(){g.Ku(this.Ab(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.hs(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ab().appendChild(b);var c=this.annotation.gf();c&&p4(this,b,c,this.annotation.id,a.session_data);Hlb(this,a)};
z4.prototype.show=function(){if(!this.isActive&&(y4.prototype.show.call(this),this.N||(this.iB(),this.N=!0),g.hs(this.Ab(),!0),this.isActive=!0,this.B)){try{Elb(this,this.B)}catch(a){}g.Ku(this.context.J.getRootNode(),"ytp-branding-shown")}};
z4.prototype.hide=function(){this.isActive&&(y4.prototype.hide.call(this),g.hs(this.Ab(),!1),this.isActive=!1,g.Mu(this.context.J.getRootNode(),"ytp-branding-shown"))};
z4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);y4.prototype.destroy.call(this)};g.w(Jlb,y4);g.k=Jlb.prototype;
g.k.iB=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ab().setAttribute("aria-hidden","true");this.Ab().setAttribute("aria-label","Promotion");this.Ab().tabIndex=0;var e=this.annotation.gf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&p4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Kn(f,j4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&p4(this,
this.Ab(),e,this.annotation.id,b.session_data,void 0,c)}g.Ku(this.j,"iv-click-target");e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.Ku(this.j,"iv-click-target"),e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ra(this.B,"click",function(q){Mlb(a,5E3,q)});
c.appendChild(this.B);g.hs(this.B,!1);this.context.j.Ra(this.Ab(),"mouseover",this.R6,this);this.context.j.Ra(this.Ab(),"mouseout",this.Q6,this);this.context.j.Ra(this.Ab(),"touchend",function(q){Mlb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ra(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.M6:this.L6,this);c.appendChild(this.C);g.Lu(this.Ab(),d);h&&(g.bf(this.Ab(),h),n&&h.appendChild(n));g.bf(this.Ab(),this.N);g.bf(this.Ab(),c)};
g.k.show=function(){this.isActive||(y4.prototype.show.call(this),this.Y||(this.iB(),this.Y=!0),g.hs(this.Ab(),!0),g.ag(function(){g.Mu(this.Ab(),"iv-promo-inactive")},100,this),this.Ab().removeAttribute("aria-hidden"),this.isActive=!0,Olb(this),Klb(this),Llb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Ku(this.Ab(),"iv-promo-inactive"),this.isActive=!1,this.Ab().setAttribute("aria-hidden","true"))};
g.k.uL=function(a,b,c,d,e,f){return this.isCollapsed?!1:y4.prototype.uL.call(this,a,b,c,d,e,f)};
g.k.R6=function(a){this.Z=!0;Mlb(this,500,a)};
g.k.Q6=function(){this.Z=!1;Nlb(this)};
g.k.L6=function(a){a.stopPropagation();this.hide()};
g.k.M6=function(a){a.stopPropagation();Olb(this);this.isCollapsed=!0;g.Ku(this.Ab(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();y4.prototype.destroy.call(this)};g.w(Qlb,g.FV);g.k=Qlb.prototype;g.k.Kh=function(a,b){if(!emb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.s2(b))&&Vlb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(rlb(this.j,b),U3(this.player)),!0}return null};
g.k.getOptions=function(){return emb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.vu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.UT(b)||g.fU(this.player.app)?!1:1===c&&!b.CU||a.Na.get(b.videoId)||g.IT(b)||g.sSa(b)?!0:!1};
g.k.AJ=function(){if(this.C){var a=this.player.kb().getVideoContentRect(!0);g.fs(this.C.element,a.width,a.height);g.bs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Yk();a=this.j;b=b.width;g.Ou(a.D,"iv-drawer-small",426>=b);g.Ou(a.D,"iv-drawer-big",1280<=b)}};
g.k.J1=function(a){Slb(this,a.state);g.FG(a.state,2)&&(this.Pk()&&this.ip()&&2!==this.player.getPresentingPlayerType()&&this.rB(!1),this.qB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.MB(h)&&h.responseXML?h.responseXML:null)&&(Vlb(b,h),g.Ku(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.FV.prototype.load.call(this);Slb(this,this.player.Rb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.ZC()&&(a=Wlb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Xlb(e,f);f=f&&(f.MM||f.ZG);if(!c.Fx||f)c.Xa?Tlb(this,c.Xa,e):(this.Bx=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.HT(h))&&!b.Y&&amb(b,h)},this.player.addEventListener("videodatachange",this.Bx));
g.uU(this.player,this.C.element,4);this.AJ();(f=g.IT(c))&&$lb(this,f);(f=g.sSa(c))&&f.featuredChannel&&dmb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Vg=g.Me("ytp-cards-button",this.player.getRootNode());g.HT(c)&&amb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&Tlb(this,b.Xa,a)};
g.k.unload=function(){this.player.lf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,U3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.Y=!1;this.K={};this.B.hide();g.FV.prototype.unload.call(this);this.C.detach();this.Bx&&(this.player.removeEventListener("videodatachange",this.Bx),this.Bx=null)};
g.k.lZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Ylb(this):this.load())};
g.k.Pk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.Y};
g.k.ip=function(){return!!this.j&&this.j.C};
g.k.rB=function(a,b,c){b=void 0===b?!1:b;this.Pk();this.j&&(a?c?r4(this.j,c,b):r4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):s4(this.j))};
g.k.qB=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.lZ,this);g.Mu(this.player.getRootNode(),g.ZY.IV_DRAWER_OPEN);for(var a=this.ma,b=g.uu,c=0,d=a.length;c<d;c++)b.Qj(a[c]);this.ma.length=0;g.FV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.J(this,a);return a.element};g.EV("annotations_module",Qlb);g.EV("creatorendscreen",Kkb);})(_yt_player);
